name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello man"
      - name: Print Goodbye
        run: echo "Goodbye"
      - name: Multiline commands
        run: |
            echo "first output"
            echo "second output"
